# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ BaileyJM02 ]
  pull_request:
    branches: [ BaileyJM02 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: |
          mkdir -p pdfs
          ls -lah

      # Run Markdown to PDF GitHub Action
      - name: Create PDF and HTML
        uses: BaileyJM02/markdown-to-pdf@master
        with:
          input_dir: docs
          output_dir: pdfs
          theme: docs/assets/style.css
          images_dir: docs/assets
          image_import: ./assets
          build_html: true

      # Upload artefacts
      - uses: actions/upload-artifact@v2.2.0
        with:
          path: pdfs/*
